
import { EventType } from '@/utils/types/eventBus';
import { Notification } from '@/components/shared/notifications/types';

// Import all mappings from the new modular structure
import {
  EVENT_TITLE_MAP,
  EVENT_TO_NOTIFICATION_TYPE,
  EVENT_TO_PRIORITY,
  RELEASE_EVENT_RECIPIENTS,
  RELEASE_EVENT_CHANNELS,
  PROBLEM_EVENT_RECIPIENTS,
  PROBLEM_EVENT_CHANNELS,
  KEDB_EVENT_RECIPIENTS,
  KEDB_EVENT_CHANNELS,
  KNOWLEDGE_EVENT_RECIPIENTS,
  KNOWLEDGE_EVENT_CHANNELS
} from './mappings';

// Re-export everything to maintain backward compatibility
export {
  EVENT_TITLE_MAP,
  EVENT_TO_NOTIFICATION_TYPE,
  EVENT_TO_PRIORITY,
  RELEASE_EVENT_RECIPIENTS,
  RELEASE_EVENT_CHANNELS,
  PROBLEM_EVENT_RECIPIENTS,
  PROBLEM_EVENT_CHANNELS,
  KEDB_EVENT_RECIPIENTS,
  KEDB_EVENT_CHANNELS,
  KNOWLEDGE_EVENT_RECIPIENTS,
  KNOWLEDGE_EVENT_CHANNELS
};
