
import { EventType } from '@/utils/types/eventBus';

/**
 * Maps event types to user-friendly notification titles
 */
export const EVENT_TITLE_MAP: Record<EventType, string> = {
  'ticket.created': 'New ticket created',
  'ticket.updated': 'Ticket updated',
  'ticket.assigned': 'Ticket assigned',
  'ticket.resolved': 'Ticket resolved',
  'ticket.closed': 'Ticket closed',
  'ticket.reopened': 'Ticket reopened',
  'change.created': 'New change request',
  'change.updated': 'Change request updated',
  'change.approved': 'Change request approved',
  'change.rejected': 'Change request rejected',
  'change.implemented': 'Change implemented',
  'problem.created': 'New problem record',
  'problem.updated': 'Problem record updated',
  'problem.resolved': 'Problem resolved',
  'problem.assigned': 'Problem assigned',
  'problem.rootCauseIdentified': 'Root cause identified',
  'problem.workaroundAvailable': 'Workaround available',
  'problem.closed': 'Problem closed',
  'sla.warning': 'SLA Warning',
  'sla.breached': 'SLA Breached',
  'task.created': 'New task created',
  'task.updated': 'Task updated',
  'task.assigned': 'Task assigned',
  'task.dueDateApproaching': 'Task due date approaching',
  'task.overdue': 'Task overdue',
  'task.statusChanged': 'Task status changed',
  'task.completed': 'Task completed',
  'release.created': 'New release created',
  'release.updated': 'Release updated',
  'release.deployed': 'Release deployed',
  'release.planApproved': 'Release plan approved',
  'release.readyForTest': 'Release ready for testing',
  'release.testCompleted': 'Release testing completed',
  'release.scheduledDeployment': 'Release deployment scheduled',
  'release.deploymentStarted': 'Release deployment started',
  'release.deploymentCompleted': 'Release deployment completed',
  'release.rollback': 'Release rollback initiated',
  'knowledge.created': 'New article created',
  'knowledge.updated': 'Article updated',
  'knowledge.published': 'Article published',
  'asset.created': 'New asset added',
  'asset.updated': 'Asset updated',
  'asset.retired': 'Asset retired',
  'test.created': 'New test case created',
  'test.executed': 'Test executed',
  'test.passed': 'Test passed',
  'test.failed': 'Test failed',
  'knownError.created': 'New known error added',
  'knownError.updated': 'Known error updated',
  'knownError.workaroundUpdated': 'Workaround updated',
  'knownError.planToFix': 'Fix scheduled',
  'knownError.resolved': 'Known error resolved',
  // Backlog item events
  'backlogItem.created': 'New backlog item created',
  'backlogItem.priorityChanged': 'Backlog item priority changed',
  'backlogItem.addedToSprint': 'Backlog item added to sprint',
  'backlogItem.removedFromSprint': 'Backlog item removed from sprint',
  'backlogItem.statusChanged': 'Backlog item status changed',
  'backlogItem.readyForReview': 'Backlog item ready for review',
  'backlogItem.completed': 'Backlog item completed',
  // Reminder events
  'reminder.upcoming': 'Reminder coming up',
  'reminder.due': 'Reminder now due',
  'reminder.recurring': 'Recurring reminder',
  'reminder.snoozed': 'Reminder snoozed',
  'reminder.canceled': 'Reminder canceled',
  // Test case events
  'testCase.created': 'New test case created',
  'testCase.updated': 'Test case updated',
  // Test execution events
  'testExecution.scheduled': 'Test execution scheduled',
  'testExecution.started': 'Test execution started',
  'testExecution.failed': 'Test execution failed',
  'testExecution.completed': 'Test execution completed',
  'testExecution.blocked': 'Test execution blocked'
};

