
/**
 * Core event type definitions
 */

// String literal types for events
export type EventType = 
  // Ticket events
  | 'ticket.created'
  | 'ticket.updated'
  | 'ticket.assigned'
  | 'ticket.resolved'
  | 'ticket.closed'
  | 'ticket.reopened'
  // Incident specific events
  | 'incident.created'
  | 'incident.updated'
  | 'incident.assigned'
  | 'incident.resolved'
  | 'incident.resolved.success'
  | 'incident.resolved.partial'
  | 'incident.closed'
  | 'incident.reopened'
  | 'incident.created.p1'
  | 'incident.created.p2'
  | 'incident.created.p3'
  | 'incident.created.p4'
  | 'incident.escalated'
  | 'incident.escalated.critical'
  | 'incident.escalated.high'
  | 'incident.updated.critical'
  // Service request specific events
  | 'service.created'
  | 'service.updated'
  | 'service.assigned'
  | 'service.resolved'
  | 'service.closed'
  | 'service.reopened'
  | 'service.approved'
  | 'service.rejected'
  | 'service.created.high'
  | 'service.created.medium'
  | 'service.created.low'
  // Change events
  | 'change.created'
  | 'change.updated'
  | 'change.approved'
  | 'change.rejected'
  | 'change.implemented'
  | 'change.rollback'
  | 'change.emergency.created'
  | 'change.emergency.approved'
  | 'change.implemented.success'
  | 'change.implemented.failure'
  | 'change.implemented.partial'
  | 'change.submitted'
  | 'change.reviewed'
  | 'change.tested'
  | 'change.canceled'
  // Problem events
  | 'problem.created'
  | 'problem.updated'
  | 'problem.resolved'
  | 'problem.resolved.success'
  | 'problem.resolved.partial'
  | 'problem.assigned'
  | 'problem.rootCauseIdentified'
  | 'problem.workaroundAvailable'
  | 'problem.closed'
  | 'problem.created.critical'
  | 'problem.created.high'
  // SLA events
  | 'sla.warning'
  | 'sla.warning.response'
  | 'sla.warning.resolution'
  | 'sla.warning.update'
  | 'sla.warning.approaching'
  | 'sla.warning.imminent'
  | 'sla.breached'
  | 'sla.breached.response'
  | 'sla.breached.resolution'
  | 'sla.breached.update'
  // Task events
  | 'task.created'
  | 'task.updated'
  | 'task.assigned'
  | 'task.dueDateApproaching'
  | 'task.overdue'
  | 'task.overdue.critical'
  | 'task.overdue.high'
  | 'task.overdue.medium'
  | 'task.statusChanged'
  | 'task.completed'
  | 'task.completed.success'
  | 'task.completed.partial'
  | 'task.deleted'
  // Release events
  | 'release.created'
  | 'release.updated'
  | 'release.deployed'
  | 'release.planApproved'     
  | 'release.readyForTest'     
  | 'release.testCompleted'    
  | 'release.scheduledDeployment' 
  | 'release.deploymentStarted'   
  | 'release.deploymentCompleted' 
  | 'release.deploymentCompleted.success'
  | 'release.deploymentCompleted.failure'
  | 'release.deploymentCompleted.partial'
  | 'release.rollback'         
  | 'release.verified'
  | 'release.buildStarted'
  | 'release.buildCompleted'
  | 'release.buildCompleted.success'
  | 'release.buildCompleted.failure'
  | 'release.canceled'
  // Asset events
  | 'asset.created'
  | 'asset.updated'
  | 'asset.retired'
  | 'asset.expiring'
  | 'asset.expiring.approaching'
  | 'asset.expiring.imminent'
  | 'asset.maintenance.scheduled'
  // Test events
  | 'test.created'
  | 'test.executed'
  | 'test.passed'
  | 'test.failed'
  | 'test.failed.critical'
  | 'test.failed.high'
  // Knowledge events      
  | 'knowledge.created'        
  | 'knowledge.updated'        
  | 'knowledge.published'      
  // Known Error events    
  | 'knownError.created'        
  | 'knownError.updated'        
  | 'knownError.workaroundUpdated' 
  | 'knownError.planToFix'      
  | 'knownError.resolved'       
  // Backlog Item events   
  | 'backlogItem.created'         
  | 'backlogItem.priorityChanged' 
  | 'backlogItem.addedToSprint'   
  | 'backlogItem.removedFromSprint' 
  | 'backlogItem.statusChanged'   
  | 'backlogItem.readyForReview'  
  | 'backlogItem.completed'
  | 'backlogItem.completed.success'
  | 'backlogItem.completed.partial'
  // Reminder events       
  | 'reminder.upcoming'           
  | 'reminder.upcoming.approaching'
  | 'reminder.upcoming.imminent'
  | 'reminder.due'                
  | 'reminder.recurring'          
  | 'reminder.snoozed'            
  | 'reminder.canceled'           
  // Test Case events      
  | 'testCase.created'            
  | 'testCase.updated'            
  // Test Execution events 
  | 'testExecution.scheduled'     
  | 'testExecution.started'       
  | 'testExecution.failed'        
  | 'testExecution.failed.critical'
  | 'testExecution.failed.high'
  | 'testExecution.completed'     
  | 'testExecution.completed.success'
  | 'testExecution.completed.partial'
  | 'testExecution.blocked';      

// Standardized event qualifiers
export type PriorityQualifier = 'p1' | 'p2' | 'p3' | 'p4';
export type SeverityQualifier = 'critical' | 'high' | 'medium' | 'low';
export type TimeQualifier = 'approaching' | 'imminent';
export type SLATypeQualifier = 'response' | 'resolution' | 'update';
export type OutcomeQualifier = 'success' | 'failure' | 'partial';
