
import {
  LayoutDashboard,
  AlarmClock,
  HelpCircle,
  Calendar,
  Blocks,
  NotebookTabs,
  RefreshCw,
  Package,
  ShieldCheck,
  Settings,
  Network,
  Database,
  FileText,
  CheckSquare,
  Bug,
  TestTube2,
  Users,
  SlidersHorizontal,
  CheckCircle2,
} from 'lucide-react';
import { NavItem } from './types';

export const navigationItems: NavItem[] = [
  {
    name: 'Dashboard',
    title: 'Dashboard',
    href: '/dashboard',
    path: '/dashboard',
    icon: LayoutDashboard,
  },
  {
    name: 'Incidents',
    title: 'Incidents',
    href: '/incidents',
    path: '/incidents',
    icon: AlarmClock,
  },
  {
    name: 'Service Requests',
    title: 'Service Requests',
    href: '/service-requests',
    path: '/service-requests',
    icon: HelpCircle,
  },
  {
    name: 'Problems',
    title: 'Problems',
    href: '/problems',
    path: '/problems',
    icon: Blocks,
  },
  {
    name: 'Changes',
    title: 'Changes',
    href: '/changes',
    path: '/changes',
    icon: RefreshCw,
  },
  {
    name: 'Releases',
    title: 'Releases',
    href: '/releases',
    path: '/releases',
    icon: Package,
  },
  {
    name: 'Tasks',
    title: 'Tasks',
    href: '/tasks',
    path: '/tasks',
    icon: CheckCircle2,
  },
  {
    name: 'Backlog',
    title: 'Backlog',
    href: '/backlog',
    path: '/backlog',
    icon: NotebookTabs,
  },
  {
    name: 'My Approvals',
    title: 'My Approvals',
    href: '/approvals',
    path: '/approvals',
    icon: CheckSquare,
  },
  {
    name: 'Calendar',
    title: 'Calendar',
    href: '/calendar',
    path: '/calendar',
    icon: Calendar,
  },
  {
    name: 'Assets',
    title: 'Assets',
    href: '/assets',
    path: '/assets',
    icon: Database,
  },
  {
    name: 'Service Catalog',
    title: 'Service Catalog',
    href: '/services',
    path: '/services',
    icon: Network,
  },
  {
    name: 'Knowledge',
    title: 'Knowledge',
    href: '/knowledge',
    path: '/knowledge',
    icon: FileText,
  },
  {
    name: 'Security',
    title: 'Security',
    href: '/security',
    path: '/security',
    icon: ShieldCheck,
  },
  {
    name: 'Settings',
    title: 'Settings',
    href: '/settings',
    path: '/settings',
    icon: Settings,
  },
  {
    name: 'Test Management',
    title: 'Test Management',
    href: '/testing',
    path: '/testing',
    icon: TestTube2,
  },
  {
    name: 'Bug Tracking',
    title: 'Bug Tracking',
    href: '/bugs',
    path: '/bugs',
    icon: Bug,
  },
  {
    name: 'User Management',
    title: 'User Management',
    href: '/user-management',
    path: '/user-management',
    icon: Users,
  },
  {
    name: 'Admin',
    title: 'Admin Settings',
    href: '/admin',
    path: '/admin',
    icon: SlidersHorizontal,
  },
];
